name: Pytest for Dingo-GW on Python 3.10

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies if cache missed
        if: steps.dependencies.outputs.cache-hit != 'true'
        run: |
          pip install --upgrade pip
          pip install --editable .[dev]

      - name: Run Pytest
        run: |
          pytest --junit-xml=pytest-report.xml tests/

      - name: Upload Pytest Report
        uses: actions/upload-artifact@v3
        with:
          name: pytest-report.xml
          path: pytest-report.xml
          retention-days: 30
