name: Pytest for Dingo-GW on Python 3.10

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Cache dependencies
        uses: actions/cache@v3
        id: dependencies
        with:
          key: ${{ runner.os }}-dependencies-${{ hashFiles('pyproject.toml') }}
          paths:
            - ~/.cache/pip/

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -z "${{ steps.dependencies.outputs.cache-hit }}" ]; then
            pip install --editable .[dev]
          fi

      - name: Run Pytest
        run: |
          pytest --junit-xml=pytest-report.xml --cov=dingo tests/

      - name: Upload Pytest Report
        uses: actions/upload-artifact@v3
        with:
          name: pytest-report.xml
          path: pytest-report.xml
